import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@helpers/cn";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

// import localFont from 'next/font/local';
// const sora = localFont({
//   src: './fonts/Sora.woff',
//   variable: '--font-sora',
//   weight: '100 900',
// });

// const inter = Inter({
//   subsets: ["latin"], // Add other subsets if necessary
// });

export const metadata: Metadata = {
  title: "GainWix.AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased relative font-Sora")}>
        <div className="w-full  fixed  left-0 z-50">
          <NavBar />
        </div>
        <div className="relative top-20">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
